import os

DOMAIN_NAME = os.environ.get("ARTEMIS_DOMAIN_NAME", "")
MAINTENANCE_MODE = os.environ.get("ARTEMIS_MAINTENANCE_MODE", "false").lower() == "true"
MAINTENANCE_MODE_MESSAGE = os.environ.get("ARTEMIS_MAINTENANCE_MODE_MESSAGE")
MAINTENANCE_MODE_RETRY_AFTER = os.environ.get("ARTEMIS_MAINTENANCE_MODE_RETRY_AFTER")
