version: "3"
services:
  engine:
    image: "${ECR}/${APPLICATION}/engine:latest"
    scale: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/artemis/work:/work
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-region: ${REGION}
        awslogs-group: ${LOG_GROUP}
        awslogs-multiline-pattern: "^\\{(?:[^{}]|\\{(?:[^{}]|\\{[^{}]*\\})*\\})*\\}$$"
        tag: engine-${INSTANCE_ID}-{{.ID}}
  db_maint:
    image: "${ECR}/${APPLICATION}/db_maintenance:latest"
    container_name: "db_maint"
    env_file:
      - .env
