[tool.ruff]
line-length = 120
target-version = "py39"

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["engine", "utilities/scale_down"]
known_third_party = ["boto3", "botocore", "django", "pytest"]
known_first_party = [
    "artemislib",
    "artemisdb",
    "artemisapi",
    "groups",
    "groups_keys",
    "groups_members",
    "ci_tools",
    "sbom_components",
    "sbom_licenses",
    "scans_batch",
    "search_repositories",
    "search_scans",
    "search_vulnerabilities",
    "scan_scheduler",
    "system_status",
    "repo",
    "users",
    "users_keys",
    "users_services",
    "authorizer",
    "api_runner",
    "db_cleanup",
    "system_allowlist",
    "end_to_end_tests",
    "scale_down",
    "json_report"
]

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "standard"
include = [
    "engine",
    "lambdas",
    "libs",
    "utilities",
]
exclude = [
    "**/.eggs",
    "**/build",
    "**/dist",
]
extraPaths = [
    "engine",
    "lambdas/api/authorizer",
    "lambdas/api/groups",
    "lambdas/api/groups_keys",
    "lambdas/api/groups_members",
    "lambdas/api/repo",
    "lambdas/api/system_services",
    "lambdas/api/users",
    "lambdas/api/users_keys",
    "lambdas/api/users_services",
    "lambdas/events/event_dispatch",
    "lambdas/events/splunk_handler",
    "lambdas/generators/json_report",
    "lambdas/generators/sbom_report",
    "lambdas/scheduled/scan_scheduler",
    "libs/artemisapi",
    "libs/artemisdb",
    "libs/artemislib",
]
ignore = [
    # Type checking for Django models is currently problematic.
    "libs/artemisdb/artemisdb/artemisdb/models.py",
]
executionEnvironments = [
    { root = "utilities/api_runner", extraPaths = ["lambdas/api"] },
]
