[project]
name = "artemis-backend"
version = "2.7.0"
requires-python = ">= 3.13"
dependencies = [
    "artemislib",
    "artemisdb",
    "artemisapi",
    "aiohttp~=3.13",
    "graphql-query~=1.4",
    "joserfc~=1.2",
    "packaging==23.2",       # Must match version in Makefile.
    "pyyaml~=6.0",
]

[dependency-groups]
lambda-core = [
    "aws-lambda-powertools~=3.25",
]
engine = [
    "awscli~=1.44",
    "docker~=7.1",
    "json-stream~=2.4",
    "pydantic==2.12.5",
    "PyGithub~=2.7",
    "sqlparse~=0.5",
    "urllib3~=2.6",
]
dev = [
    "autopep8~=2.3",
    "boto3-stubs[ec2,lambda,s3,secretsmanager,sqs]~=1.41",
    "cfn-lint==1.44.0", # Must match version in Makefile.
    "debugpy~=1.8",
    "flake8~=7.2",
    "isort~=8.0",
    "moto[awslambda,ec2,s3,secretsmanager,sqs]~=5.1",
    "pylint~=4.0",
    "pyright~=1.1",
    "pytest~=9.0",
    "pytest-asyncio~=1.3",
    "pytest-cov~=7.0",
    "pytest-httpserver~=1.1",
    "pytest-subtests~=0.14",
    "pytest-xdist~=3.6",
    "python-dotenv~=1.1",
    "responses~=0.26",
    "ruff==0.15.22",
    "xmltodict~=1.0",
]

[tool.uv.sources]
artemislib = { path = "libs/artemislib" }
artemisdb = { path = "libs/artemisdb" }
artemisapi = { path = "libs/artemisapi" }

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["engine", "utilities/scale_down"]
known_third_party = ["boto3", "botocore", "django", "pytest"]
known_first_party = [
    "artemislib",
    "artemisdb",
    "artemisapi",
    "groups",
    "groups_keys",
    "groups_members",
    "ci_tools",
    "sbom_components",
    "sbom_licenses",
    "scans_batch",
    "search_repositories",
    "search_scans",
    "search_vulnerabilities",
    "scan_scheduler",
    "system_status",
    "repo",
    "users",
    "users_keys",
    "users_services",
    "authorizer",
    "api_runner",
    "db_cleanup",
    "system_allowlist",
    "end_to_end_tests",
    "scale_down",
    "json_report"
]

[tool.pyright]
pythonVersion = "3.13"
typeCheckingMode = "standard"
include = [
    "engine",
    "lambdas",
    "libs",
    "utilities",
]
exclude = [
    "**/.eggs",
    "**/build",
    "**/dist",
]
extraPaths = [
    "engine",
    "lambdas/api/authorizer",
    "lambdas/api/groups",
    "lambdas/api/groups_keys",
    "lambdas/api/groups_members",
    "lambdas/api/repo",
    "lambdas/api/system_services",
    "lambdas/api/users",
    "lambdas/api/users_keys",
    "lambdas/api/users_services",
    "lambdas/events/event_dispatch",
    "lambdas/events/splunk_handler",
    "lambdas/generators/json_report",
    "lambdas/generators/sbom_report",
    "lambdas/scheduled/scan_scheduler",
    "libs/artemisapi",
    "libs/artemisdb",
    "libs/artemislib",
]
ignore = [
    # Type checking for Django models is currently problematic.
    "libs/artemisdb/artemisdb/artemisdb/models.py",
]
executionEnvironments = [
    { root = "utilities/api_runner", extraPaths = ["lambdas/api"] },
]
