const runMigrations = () => {
	// REPLACE ME: HERE YOU CAN DEFINE MIGRATION TASKS THAT WILL RUN WHEN THE USER ACCESSES THE MAIN PAGE
	// E.G., IF YOU NEED TO MIGRATE LEGACY SETTING "foo" TO CURRENT SETTING "bar"
};
export default runMigrations;
