import os

KEY_REMINDER_FROM_EMAIL = os.environ.get("ARTEMIS_KEY_REMINDER_FROM_EMAIL")
KEY_REMINDER_SES_REGION = os.environ.get("ARTEMIS_KEY_REMINDER_SES_REGION", "us-east-2")
ARTEMIS_DOMAIN = os.environ.get("ARTEMIS_DOMAIN")
