# Generated by Django 3.1 on 2020-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0002_auto_20201002_1434"),
    ]

    operations = [
        migrations.AddField(model_name="user", name="last_login", field=models.DateTimeField(null=True)),
    ]
