# Generated by Django 3.1 on 2020-11-04 15:03

import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0004_auto_20201028_1640"),
    ]

    operations = [
        migrations.AddField(model_name="apikey", name="admin", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="apikey",
            name="features",
            field=models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.AddField(model_name="user", name="admin", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="user",
            name="features",
            field=models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
    ]
