# Generated by Django 3.1.7 on 2021-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0014_auto_20210405_1139"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=256, unique=True)),
                ("value", models.CharField(max_length=256)),
                ("expires", models.DateTimeField()),
            ],
        ),
    ]
