# Generated by Django 3.2.4 on 2021-06-10 13:20

import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0015_cacheitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginresult",
            name="alerts",
            field=models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.AddField(
            model_name="pluginresult",
            name="debug",
            field=models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.AddField(
            model_name="scan",
            name="alerts",
            field=models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="debug",
            field=models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder, null=True),
        ),
    ]
