# Generated by Django 3.2.4 on 2021-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0016_auto_20210610_1320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cacheitem",
            name="expires",
            field=models.DateTimeField(null=True),
        ),
    ]
