# Generated by Django 3.2.4 on 2021-06-16 12:47

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


def set_created_before_expires(apps, schema_editor):
    cache_items = apps.get_model("artemisdb", "cacheitem")
    for item in cache_items.objects.filter(expires__isnull=False):
        item.created = item.expires + datetime.timedelta(days=-7)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0017_alter_cacheitem_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cacheitem",
            name="expires",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cacheitem",
            name="accessed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cacheitem",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.fromtimestamp(0, tz=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cacheitem",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cacheitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(set_created_before_expires),
    ]
