# Generated by Django 3.2.4 on 2021-06-22 10:13

import django.db.models.deletion
from django.db import migrations, models

import artemisdb.artemisdb.consts


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0018_refactor_cacheitem_add_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_id", models.UUIDField(unique=True)),
                (
                    "report_type",
                    models.CharField(choices=[(artemisdb.artemisdb.consts.ReportType["PDF"], "pdf")], max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (artemisdb.artemisdb.consts.ReportStatus["QUEUED"], "queued"),
                            (artemisdb.artemisdb.consts.ReportStatus["PROCESSING"], "processing"),
                            (artemisdb.artemisdb.consts.ReportStatus["COMPLETED"], "completed"),
                            (artemisdb.artemisdb.consts.ReportStatus["FAILED"], "failed"),
                            (artemisdb.artemisdb.consts.ReportStatus["ERROR"], "error"),
                            (artemisdb.artemisdb.consts.ReportStatus["TERMINATED"], "terminated"),
                        ],
                        max_length=64,
                    ),
                ),
                ("requested", models.DateTimeField(auto_now_add=True)),
                ("completed", models.DateTimeField(null=True)),
                ("scan_id", models.UUIDField()),
                ("filters", models.JSONField(default=dict)),
                ("s3_key", models.CharField(max_length=256, null=True)),
                (
                    "created_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="artemisdb.user"),
                ),
            ],
        ),
    ]
