# Generated by Django 3.2.5 on 2021-07-21 10:32

import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0019_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="application_metadata",
            field=models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
    ]
