# Generated by Django 3.2.5 on 2021-12-13 12:57

import django.db.models.deletion
import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0027_auto_20211206_1125"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="schedule",
        ),
        migrations.CreateModel(
            name="ScanScheduleRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.UUIDField(unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("categories", models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder)),
                ("plugins", models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder)),
                ("depth", models.IntegerField(default=500)),
                ("include_dev", models.BooleanField(default=False)),
                (
                    "schedule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.scanschedule"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scan",
            name="schedule_run",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="artemisdb.scanschedulerun"
            ),
        ),
        migrations.CreateModel(
            name="ScanScheduleRetry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("retry_id", models.UUIDField(unique=True)),
                ("scan_config", models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder)),
                ("retry_time", models.DateTimeField()),
                ("count_remaining", models.PositiveSmallIntegerField(default=3)),
                ("errors", models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder)),
                ("repo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.repo")),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.scanschedulerun"),
                ),
            ],
            options={
                "unique_together": {("repo", "run")},
            },
        ),
    ]
