# Generated by Django 3.2.10 on 2021-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0028_auto_20211213_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanschedule",
            name="time_of_day",
            field=models.TimeField(null=True),
        ),
    ]
