# Generated by Django 3.2.12 on 2022-02-25 10:09

import simplejson.encoder
from django.db import migrations, models


def migrate_metadata(apps, _schema_editor):
    Scan = apps.get_model("artemisdb", "Scan")

    # Loop through the most recent scan for each repo that has metadata set
    for scan_object in (
        Scan.objects.exclude(application_metadata={})
        .order_by("repo", "created")
        .distinct("repo")
        .only("repo", "application_metadata")
    ):
        # Set the repo's metadata to match the scan's metadata
        scan_object.repo.application_metadata = scan_object.application_metadata
        scan_object.repo.save()


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0030_repocomponentscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="application_metadata",
            field=models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.AddField(
            model_name="repo",
            name="application_metadata_timestamps",
            field=models.JSONField(default=dict, encoder=simplejson.encoder.JSONEncoder),
        ),
        migrations.RunPython(code=migrate_metadata, reverse_code=migrations.RunPython.noop),
    ]
