# Generated by Django 3.2.13 on 2022-05-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0034_auto_20220427_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanbatch",
            name="created_by",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="artemisdb.group"),
        ),
    ]
