# Generated by Django 3.2.13 on 2022-05-20 16:52

import django.db.models.deletion
import simplejson.encoder
from django.db import migrations, models

import artemisdb.artemisdb.consts


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0036_alter_dependency_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAllowListItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_id", models.UUIDField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[(artemisdb.artemisdb.consts.SystemAllowListType["SECRET"], "secret")], max_length=64
                    ),
                ),
                ("value", models.JSONField(encoder=simplejson.encoder.JSONEncoder)),
                ("reason", models.CharField(max_length=512)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systemallowlistitem_created_by",
                        to="artemisdb.group",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systemallowlistitem_updated_by",
                        to="artemisdb.group",
                    ),
                ),
            ],
        ),
    ]
