# Generated by Django 3.2.14 on 2022-08-05 11:58

import django.db.models.deletion
import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0039_vulnerability"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoVulnerabilityScan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vuln_instance_id", models.UUIDField()),
                ("ref", models.CharField(max_length=256, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("repo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.repo")),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolves",
                        to="artemisdb.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VulnerabilityScanPlugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.JSONField(default=list, encoder=simplejson.encoder.JSONEncoder)),
                ("components", models.ManyToManyField(to="artemisdb.Component")),
                ("plugins", models.ManyToManyField(to="artemisdb.Plugin")),
                ("scan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.scan")),
                (
                    "vuln_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artemisdb.repovulnerabilityscan"
                    ),
                ),
            ],
            options={
                "unique_together": {("vuln_instance", "scan")},
            },
        ),
        migrations.AddField(
            model_name="repovulnerabilityscan",
            name="scan",
            field=models.ManyToManyField(through="artemisdb.VulnerabilityScanPlugin", to="artemisdb.Scan"),
        ),
        migrations.AddField(
            model_name="repovulnerabilityscan",
            name="vulnerability",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.vulnerability"),
        ),
        migrations.AlterUniqueTogether(
            name="repovulnerabilityscan",
            unique_together={("repo", "vulnerability", "ref")},
        ),
    ]
