# Generated by Django 3.2.15 on 2022-09-09 18:40

import django.db.models.deletion
import simplejson.encoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0040_auto_20220805_1158"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.JSONField(encoder=simplejson.encoder.JSONEncoder)),
                ("config", models.JSONField(encoder=simplejson.encoder.JSONEncoder)),
                ("plugin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="artemisdb.plugin")),
            ],
        ),
    ]
