# Generated by Django 3.2.16 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0043_auto_20230306_1227"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
