# Generated by Django 3.2.16 on 2023-03-06 16:03

from django.db import migrations


def add_basic_secret_types(apps, schema_editor):
    """
    We can't import the SecretType model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    SecretType = apps.get_model("artemisdb", "SecretType")
    for name in ["aws", "ssh", "mongo", "postgres", "redis", "urlauth", "google", "slack", "other"]:
        SecretType.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0044_secrettype"),
    ]

    operations = [
        migrations.RunPython(add_basic_secret_types),
    ]
