# Generated by Django 3.2.16 on 2023-03-22 10:25

import artemisdb.artemisdb.consts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artemisdb", "0045_secrettype_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[
                    (artemisdb.artemisdb.consts.ComponentType["UNKNOWN"], "unknown"),
                    (artemisdb.artemisdb.consts.ComponentType["NPM"], "npm"),
                    (artemisdb.artemisdb.consts.ComponentType["PYPI"], "pypi"),
                    (artemisdb.artemisdb.consts.ComponentType["GEM"], "gem"),
                    (artemisdb.artemisdb.consts.ComponentType["GO"], "go"),
                    (artemisdb.artemisdb.consts.ComponentType["PHP"], "php"),
                    (artemisdb.artemisdb.consts.ComponentType["MAVEN"], "maven"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
