# Generated by Django 3.2.23 on 2023-11-15 14:08

import artemisdb.artemisdb.consts
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0046_component_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="type",
            field=models.CharField(
                choices=[
                    (artemisdb.artemisdb.consts.PluginType["CONFIGURATION"], "configuration"),
                    (artemisdb.artemisdb.consts.PluginType["INVENTORY"], "inventory"),
                    (artemisdb.artemisdb.consts.PluginType["VULN"], "vulnerability"),
                    (artemisdb.artemisdb.consts.PluginType["SBOM"], "sbom"),
                    (artemisdb.artemisdb.consts.PluginType["SECRETS"], "secrets"),
                    (artemisdb.artemisdb.consts.PluginType["STATIC_ANALYSIS"], "static_analysis"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="pluginresult",
            name="plugin_type",
            field=models.CharField(
                choices=[
                    (artemisdb.artemisdb.consts.PluginType["CONFIGURATION"], "configuration"),
                    (artemisdb.artemisdb.consts.PluginType["INVENTORY"], "inventory"),
                    (artemisdb.artemisdb.consts.PluginType["VULN"], "vulnerability"),
                    (artemisdb.artemisdb.consts.PluginType["SBOM"], "sbom"),
                    (artemisdb.artemisdb.consts.PluginType["SECRETS"], "secrets"),
                    (artemisdb.artemisdb.consts.PluginType["STATIC_ANALYSIS"], "static_analysis"),
                ],
                max_length=64,
            ),
        ),
    ]
