# Generated by Django 3.2.23 on 2024-02-06 20:45

import artemisdb.artemisdb.consts
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artemisdb", "0048_alter_component_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_id",
            field=models.CharField(max_length=256, unique=True),
        )
    ]
