# syntax=docker/dockerfile:1

# Builder for boxed core plugins.

# Python base image.
ARG PYTHON_VER=3.13-debian13

FROM dhi.io/python:$PYTHON_VER

# Python target version for installed packages (major.minor).
ARG PYTHON_TARGET_VER=3.13

ARG LIBC=glibc

COPY --from=ghcr.io/astral-sh/uv:0.12.3 /uv /uvx /bin/

WORKDIR /src

# Download and install standalone Python distribution.
RUN --mount=type=cache,target=/root/.cache/uv \
    mkdir -p "_boxed/$LIBC" && \
    uv python install -i build/tmp "$PYTHON_TARGET_VER" && \
    mv build/tmp/cpython-*.*.*-* "_boxed/$LIBC/python"

COPY pyproject.toml .
COPY uv.lock .
COPY libs/ libs/
COPY engine/plugins/ _boxed/$LIBC/engine/plugins

RUN uv export --locked --group engine --no-dev --no-editable --no-emit-project --no-emit-local > requirements.txt

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -r requirements.txt \
        libs/artemisdb libs/artemislib \
        --target "_boxed/$LIBC/python/lib/python$PYTHON_TARGET_VER/site-packages" \
        --python-version "$PYTHON_TARGET_VER"
