# Note: This Dockerfile creates an image intended ONLY for local development and testing
# it may contain unnecessary source code and artifacts that are NOT intended for deployment

FROM node:22-trixie-slim

WORKDIR /app

# Note: don't copy all source code immediately
# just grab the package file and npm ci dependencies
# that way, the expensive dependency install can be performed ONCE in a layer
# and it's inexpensive to rebuild the container when
# modifications are made to the source code in subsequent layers
COPY package*.json hadolint.sha512 .npmrc ./

# hadolint: hadlolint unavailable via apt, so use the binary from GitHub
# it doesn't include a file checksum, so use one we've generated to validate the package
# hadolint ignore=DL3008
RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y --no-install-recommends jq ca-certificates make && \
	curl https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 \
	-o ./hadolint && \
	sha512sum -c hadolint.sha512 && \
	chmod 0766 ./hadolint && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3059
RUN npm install -g --ignore-scripts npm@^10.2.5 && \
	npm ci && \
	npx allow-scripts && \
	npm install -g --ignore-scripts serve@^14.2.1 && \
	npm ls -a

COPY . .

CMD ["npm", "run", "start"]
