# Note: This Dockerfile creates an image intended ONLY for local development and testing
# it may contain unnessary source code and artifacts that are NOT intended for deployment

FROM node:18-bullseye-slim

WORKDIR /app

# Note: don't copy all source code immediately
# just grab the package file and npm ci dependencies
# that way, the expensive dependency install can be performed ONCE in a layer
# and it's inexpensive to rebuild the container when
# modifications are made to the source code in subsequent layers
COPY package*.json hadolint.sha512 ./

# hadolint: hadlolint unavailable via apt, so use the binary from GitHub
# it doesn't include a file checksum, so use one we've generated to validate the package
# hadolint ignore=DL3008
RUN apt-get update && \
	grep security /etc/apt/sources.list > /etc/apt/security.sources.list && \
	apt-get upgrade -y && \
	apt-get upgrade -y -o Dir::Etc::Sourcelist=/etc/apt/security.sources.list && \
	apt-get install -y --no-install-recommends jq wget ca-certificates make && \
	wget --quiet \
	https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 \
	-O ./hadolint && \
	sha512sum -c hadolint.sha512 && \
	chmod 0766 ./hadolint && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3059
RUN npm install -g npm@^9.2.0 && \
	npm ci && \
	npm install -g serve@^14.1.2 && \
	npm ls -a

COPY . .
COPY publicCustom ./public/

CMD ["npm", "run", "start"]
