name: UI Unit Tests

on:
  pull_request:
    paths:
      - "ui/**"
      - ".github/workflows/test_ui.yml"

jobs:
  test:
    runs-on: artemis-ui-test-runner-4
    permissions:
      contents: read
    env:
      UI_PATH: ./ui
      NPM_VERSION: 10

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2

      - name: Install tools
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # jdx/mise-action@v3.6.1

      - name: Set up the npm version
        run: npm install --global --ignore-scripts npm@$NPM_VERSION

      - name: Install npm packages
        run: make -C $UI_PATH install

      - name: Run precommit checks (linting & testing etc)
        run: make -C $UI_PATH precommit

      - name: Save test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # actions/upload-artifact@v7.0.1
        with:
          name: ui-test
          path: ui/test-report/index.html
