name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # actions/checkout@v2.3.3
      - uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8 # actions/setup-python@v2.1.4
        with:
          python-version: "3.9"
      - name: Run tests
        env:
          ANALYZER_DJANGO_SECRET_KEY: ${{ secrets.TEST_DJANGO_SECRET_KEY }}
          ANALYZER_DB_HOST: ${{ secrets.TEST_DB_HOST }}
          ANALYZER_DB_PORT: ${{ secrets.TEST_DB_PORT }}
          ANALYZER_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          ANALYZER_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          ANALYZER_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        run: make -C backend unit-test ENV=example
